version: "3.9"

services:
  laravel.inscripciones:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-inscripciones
    ports:
      - "84:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:84
      # DB_CONNECTION: pgsql
      # DB_HOST: postgres
      # DB_PORT: 5432
      # DB_DATABASE: laravel
      # DB_USERNAME: laravel
      # DB_PASSWORD: secret
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      # - postgres
      - redis
      - rabbitmq
    networks:
      - microservicios-topicos

  # postgres:
  #   image: postgres:17-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - microservicios-topicos

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservicios-topicos

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservicios-topicos

volumes:
  # postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  microservicios-topicos:
    external: true
